import "../styles/globals.scss";
import Navbar from '../components/Navbar';
import StyledComponentsRegistry from '../libs/styled-components/StyledComponentsRegistry';
import Footer from "../components/Footer";
import Theme from "../themes/provider";
import { PageContent } from "../components/Layouts/PageContent";
import PageContainer from "../components/Layouts/PageContainer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <StyledComponentsRegistry>
          <Theme>
            <PageContainer>
              <Navbar />
              <PageContent>
                {children}
              </PageContent>
              <Footer />
            </PageContainer>
          </Theme>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
