import "../styles/globals.scss";
import Navbar from "../components/Navbar";
import StyledComponentsRegistry from "../libs/styled-components/StyledComponentsRegistry";
import Footer from "../components/Footer";
import Theme from "../themes/provider";
import { PageContent } from "../components/Layouts/PageContent";
import PageContainer from "../components/Layouts/PageContainer";
import ModalsProvider from "../state/ModalState";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body>
        <div id="tooltip-root" style={{ position: "fixed", zIndex: 9999 }} />
        <div id="modal-root" style={{ zIndex: 9999 }} />
        <StyledComponentsRegistry>
          <ModalsProvider>
            <Theme>
              <PageContainer>
                <Navbar />
                <PageContent>{children}</PageContent>
                <Footer />
              </PageContainer>
            </Theme>
          </ModalsProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
